### ISSUE TITLE
时间轴添加元素无效

### ISSUE THREAD

**Issue by policymakers** [axing521/i-love-video#1]
你好作者，我本地拉取你的项目，鼠标右键资产轴，添加任何素材，它无法在资产轴上显示

**Comment by icecai521** [comment]
你先在asset window里上传资产，然后再在下面时间轴右键添加，然后看看右侧呢

**Comment by policymakers** [comment]
> 你先在asset window里上传资产，然后再在下面时间轴右键添加，然后看看右侧呢

一样的结果，没有任何报错，我怀疑是store.showStrips 没有监听到数据变化

**Comment by icecai521** [comment]
你用8good.top这个网址ok吗

**Comment by policymakers** [comment]
> 你用8good.top这个网址ok吗

OK的，能显示。

**Comment by icecai521** [comment]
那可能你本地环境或依赖配置有问题，你自己再找找吧

**Comment by policymakers** [comment]
排查到了，是project.ts的showStrips里的判断有问题。
`s.start + s.length < this.start + this.showLength && this.start < s.start`
